language: java

env: CXX=/tmp/gcc/usr/bin/g++-4.8 CC=/tmp/gcc/usr/bin/gcc-4.8

install:
  - buildscripts/make_dependencies.sh

script:
  - export PATH=/tmp/grpc-deps/bin:$PATH
  - ./gradlew install

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

notifications:
  email: false