language: java

env:
  global:
    - CXXFLAGS=--std=c++0x

install:
  - buildscripts/make_dependencies.sh

script:
  - export PATH=/tmp/grpc-deps/bin:$PATH
  - ./gradlew install

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

notifications:
  email: false