language: java

install:
  - export PATH=/tmp/grpc-deps/bin:$PATH
  - buildscripts/make_dependencies.sh

script: ./gradlew install

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

notifications:
  email: false