sudo: required

language: java

addons:
  apt:
    packages:
      - wget

matrix:
  include:
    - env: TARGET="bazel"
    - env: TARGET="gradle"

env:
  global:
    - BAZEL_VERSION=0.9.0
    - GRADLE_OPTS=-Xmx512m
    - PROTOBUF_VERSION=3.5.1
    - LDFLAGS=-L/tmp/protobuf/lib
    - CXXFLAGS=-I/tmp/protobuf/include
    - LD_LIBRARY_PATH=/tmp/protobuf/lib

before_install:
  - buildscripts/travis-before_install.sh

install:
  - buildscripts/travis-install.sh

before_script:
  - test -z "$(git status --porcelain)" || (git status && echo Error Working directory is not clean. Forget to commit generated files? && false)

script:
  - buildscripts/travis-script.sh

after_success:
  - buildscripts/travis-after_success.sh

os:
  - linux

notifications:
  email: false

cache:
  directories:
    - /tmp/bazel
    - /tmp/protobuf-${PROTOBUF_VERSION}
    - /tmp/gradle-caches-modules-2
    - /tmp/gradle-wrapper

before_cache:
  - buildscripts/travis-before_cache.sh
